### ISSUE TITLE
call search

### ISSUE THREAD

**Issue by ddiaz2380** [tsamaya/node-leaflet-express-ejs#2]
Is it possible to add a search engine for calles and to fix the point, display a popup with a loading form?
As well as allowing you to double click on the map and open the same form.
Greetings!

**Comment by tsamaya** [comment]
Sure everything is possible. As this example uses leaflet there are plenty of examples to geocode addresses. Here is one from my friends at OpenCage https://opencagedata.com/tutorials/geocode-in-leaflet.
Feel free to fork and make a PR.
Best

**Comment by tsamaya** [comment]
closing, feel free to get in touch if you need some more information/help
